// const base = '.b-force.in/api'; //live
const base = '.b-forcefashion.in/api'; //demo

export const urls = { 
  prefix: 'http://',
  login: base + '/users/login',
  profile: base + '/users/profile',
  punchIn: base + '/attendances/punch-in',
  punchOut: base + '/attendances/punch-out',
  punchStatus: base + '/attendances/punch-status',
  geolocations: base + '/geolocations',
  customers: base + '/customers',
  complaints: base + '/complaints',
  complaintTypes: base + '/complaint-types',
  complaintFeedbackTypes: base + '/complaint-feedback-types',
  checkIn: base + '/customer-visits/check-in',
  checkOut: base + '/customer-visits/check-out',
  feedback: base + '/customer-visit-feedbacks',
  saveFeedback: base + '/customer-visits/save-feedback',
  product: base + '/brands',
  products: base + '/products',
  customerVisitStatus: base + '/customer-visits/status',
  order: base + '/orders',
  areas: base + '/areas',
  payment: base + '/payments',
  paymentType: base + '/payment-types',
  paymentType: base + '/payment-types',
  categories: base + '/categories',
  subCategories: base + '/sub-categories',
  news: base + '/news',
  banks: base + '/banks',
  note: base + '/payments/notes',
  recentPayment: base + '/payments/recent?customer_id=',
  recentOrder: base + '/orders/recent?customer_id=',
  watermark: 'http://newmahalaxmi.b-force.in/img/passi-logo.jpeg',
  dailyPerformance: base + '/performance/daily',
  activityLog: base + '/activity-logs',
  units: base + '/units',
  distributors: base + '/distributors/search',
  areaSchedules: base + '/area-schedules',
  orderSales: base + '/orders/sales',
  compAnalysis: base + '/competitor-analysis',
  customerClasses: base + '/customer-classes',
  customerChannels: base + '/customer-channels',
  customerCategories: base + '/customer-categories',
  customerNumberSearch: base + '/customers/search-by-contact-number',
};
